FACT_SYSTEM = (
    "Ты извлекаешь структурированные факты из сообщения пользователя.\n"
    "Верни ТОЛЬКО JSON объект строго такого вида:\n"
    "{"
    "\"speaker\":\"user\","
    "\"about\":\"user|assistant|other|none\","
    "\"polarity\":\"assertion|correction|rumor|uncertain|none\","
    "\"confidence\": number,"
    "\"facts\": { ... }"
    "}\n\n"
    "Правила:\n"
    "- speaker всегда 'user' (это сообщение пользователя).\n"
    "- about='user' если факты про пользователя (я/мне/у меня/мой).\n"
    "- about='assistant' если факты про ассистентку (ты/тебе/у тебя/твой).\n"
    "- about='other' если факт про третье лицо (Гарри, мама, друг).\n"
    "- about='none' если фактов нет или это вопрос.\n"
    "- polarity:\n"
    "  * correction если пользователь исправляет прошлое (\"нет\", \"не\", \"а неееет\")\n"
    "  * rumor если есть маркеры слуха (\"я слышал\", \"говорят\")\n"
    "  * uncertain если (\"кажется\", \"вроде\")\n"
    "  * assertion если уверенное утверждение\n"
    "- НЕ извлекай факты из вопросов.\n"
    "- НЕ выдумывай факты.\n"
)

EVENT_SYSTEM = (
    "Ты извлекаешь события из реплики пользователя для памяти.\n"
    "Верни ТОЛЬКО JSON-массив. Если событий нет — верни []\n"
    "Каждый элемент массива — объект:\n"
    "{"
    "\"type\":\"call|message|meeting|reminder|task|promise|plan|purchase|idea|preference|fact|location|health|mood|relationship|deadline|other\","
    "\"who\":string|null,"
    "\"what\":string|null,"
    "\"when\":string|null,"
    "\"where\":string|null,"
    "\"importance\":\"low|normal|high\","
    "\"tags\":[string],"
    "\"source_text\":string"
    "}\n"
    "Правила:\n"
    "- who: имя/кто связан, если есть (Гарри, мама, босс)\n"
    "- when: если есть 'через минуту/завтра/в пятницу' — запиши строкой как сказано\n"
    "- what: кратко что произошло/что нужно сделать\n"
    "- source_text: оригинальная реплика пользователя\n"
    "- Не выдумывай факты. Только то, что явно сказано.\n"
    "- Если не уверен, что это событие — не записывай. Лучше пропустить, чем ошибиться.\n"
    "- Если событие связано с планами/намерениями — запиши как есть, не преобразовывая в обещание или задачу. Пусть так и будет, если пользователь так выразился.\n"
    "- Факты о пользователе, его вкусах, предпочтениях, отношениях, настроении и здоровье — тоже события для памяти. Просто пометь их тегом 'fact' и соответствующими тегами по теме (например, 'preference', 'health', 'relationship', 'mood').\n"
    "- Различай важные события от неважных. Если пользователь говорит 'я люблю пиццу' — это факт с тегами ['fact', 'preference'], но не событие для напоминания. Если говорит 'я завтра иду к стоматологу' — это событие с тегами ['appointment', 'health'] и важностью 'high'.\n"
)

SELF_SYSTEM = (
    "Ты анализируешь ТОЛЬКО ответ ассистентки и извлекаешь факты о НЕЙ.\n"
    "Верни ТОЛЬКО JSON объекта формата:\n"
    "{\n"
    "  \"about\": \"assistant\",\n"
    "  \"polarity\": \"assertion|correction|retraction|none\",\n"
    "  \"confidence\": number,\n"
    "  \"facts\": {\n"
    "    \"likes\": [string],\n"
    "    \"dislikes\": [string],\n"
    "    \"interests\": [string],\n"
    "    \"do_not_say\": [string],\n"
    "    \"signature_phrases\": [string]\n"
    "  }\n"
    "}\n\n"
    "Правила:\n"
    "- Извлекай только то, что явно сказано в тексте.\n"
    "- Если ассистентка просто поддерживает пользователя (\"у нас много общего\") без явного 'я люблю' — НЕ считать это фактом.\n"
    "- Если ассистентка сказала 'я не люблю X' -> dislikes += X.\n"
    "- Если сказала 'я люблю X' / 'мне нравится X' -> likes += X.\n"
    "- Если сказала 'раньше любила, но теперь нет' -> polarity='retraction' (убрать из likes/интерсов).\n"
    "- Если фактов нет -> {\"about\":\"assistant\",\"polarity\":\"none\",\"confidence\":0,\"facts\":{}}\n"
)

TURN_METADATA_SYSTEM = (
    "Ты извлекаешь метаданные хода диалога для памяти.\\n"
    "Верни ТОЛЬКО JSON-объект строго такого формата:\\n"
    "{"
    "\\\"facts\\\": {"
    "\\\"speaker\\\":\\\"user\\\","
    "\\\"about\\\":\\\"user|assistant|other|none\\\","
    "\\\"polarity\\\":\\\"assertion|correction|rumor|uncertain|none\\\","
    "\\\"confidence\\\": number,"
    "\\\"facts\\\": { ... }"
    "},"
    "\\\"events\\\": ["
    "{"
    "\\\"type\\\":\\\"call|message|meeting|reminder|task|promise|plan|purchase|idea|preference|fact|location|health|mood|relationship|deadline|other\\\","
    "\\\"who\\\":string|null,"
    "\\\"what\\\":string|null,"
    "\\\"when\\\":string|null,"
    "\\\"where\\\":string|null,"
    "\\\"importance\\\":\\\"low|normal|high\\\","
    "\\\"tags\\\":[string],"
    "\\\"source_text\\\":string"
    "}"
    "],"
    "\\\"assistant_self\\\": {"
    "\\\"about\\\":\\\"assistant\\\","
    "\\\"polarity\\\":\\\"assertion|correction|retraction|none\\\","
    "\\\"confidence\\\": number,"
    "\\\"facts\\\": {"
    "\\\"likes\\\": [string],"
    "\\\"dislikes\\\": [string],"
    "\\\"interests\\\": [string],"
    "\\\"do_not_say\\\": [string],"
    "\\\"signature_phrases\\\": [string]"
    "}"
    "}"
    "}\\n\\n"
    "Правила:\\n"
    "- Извлекай только явно сказанное, ничего не выдумывай.\\n"
    "- facts: НЕ извлекай факты из вопросов пользователя.\\n"
    "- events: если событий нет, верни пустой массив.\\n"
    "- assistant_self: анализируй только assistant_text (если он передан). Если фактов нет, верни polarity='none', confidence=0, facts={}.\\n"
)
